name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: 11

      - name: Install Dependency
        run: go get -v -t ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
