name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Install Other dependencies
        run: sudo apt-get update && sudo apt-get install gcc libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Install Go Dependency
        run: go get -v -t ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
